const DESIGN_MAINWINDOW_WIDTH = 1366
const DESIGN_MAINWINDOW_HEIGHT = 768
const REFRENCE_SCREEN_WIDTH= 1920
const REFRENCE_SCREEN_HEIGHT = 1080
const DESIGN_LAUNCHPAGE_WIDTH = 600
const DESIGN_LAUNCHPAGE_HEIGHT = 300